# prettier v3.0
plugins:
    - "@trivago/prettier-plugin-sort-imports"
    - "@prettier/plugin-php"

# prettier-plugin-sort-imports v4.2
importOrder:
    - "polyfills$"
    - "^node:"
    - "<THIRD_PARTY_MODULES>"
    - "[.][.]/core/"
    - "^[.][.]/"
    - "^[.]/"
importOrderSortSpecifiers: true
importOrderParserPlugins:
    - typescript
    - importAssertions
    - decorators-legacy
tabWidth: 4
useTabs: true
overrides:
    - files: "assets/**/*.scss"
      options:
          tabWidth: 4
          parser: "scss"
          useTabs: true
          singleQuote: true
    - files: "assets/**/*.js"
      options:
          tabWidth: 4
          useTabs: true
    - files: "*.php"
      options:
          parser: "php"
          tabWidth: 4
          useTabs: true
